Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-precise12042-x64-vbox43"
  config.vm.box_url = "http://box.puphpet.com/ubuntu-precise12042-x64-vbox43.box"

  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.hostname = "fof.local"

  config.vm.synced_folder "../www", "/var/www", id: "vagrant-root", group: "www-data", :mount_options =>  ["dmode=777","fmode=666"]
  config.vm.synced_folder "../shared", "/home/shared", id: "vagrant-root", :nfs => false

  config.vm.usable_port_range = (2200..2250)
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "FOF-vm-box"]
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--memory", "1024"]
    virtualbox.customize ["setextradata", :id, "--VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end

  config.vm.provision :shell, :path => "shell/initial-setup.sh"
  config.vm.provision :shell, :path => "shell/update-puppet.sh"
  config.vm.provision :shell, :path => "shell/librarian-puppet-vagrant.sh"
  config.vm.provision :puppet do |puppet|
    puppet.facter = {
      "ssh_username" => "vagrant"
    }

    puppet.manifests_path = "puppet/manifests"
    puppet.options = ["--verbose", "--hiera_config /vagrant/hiera.yaml", "--parser future"]
  end
  config.vm.provision :shell, :path => "shell/install_phalcon.sh"
  config.vm.provision :shell, :path => "shell/install_phalcon_devtools.sh"
  config.vm.provision :shell, :path => "shell/install_phpqatools.sh"
  config.vm.provision :shell, :path => "shell/install_mongodb.sh"
  config.vm.provision :shell, :path => "shell/install_ruby_gems.sh"
  config.vm.provision :shell, :path => "shell/install_nodejs.sh"


  config.ssh.username = "vagrant"

  config.ssh.shell = "bash -l"

  config.ssh.keep_alive = true
  config.ssh.forward_agent = false
  config.ssh.forward_x11 = false
  config.vagrant.host = :detect
end